version: '3.5'

services:
  # Configuration for Hub+Proxy
  jupyterhub:
    build: jupyterhub
    image: jupyterhub-hub
    container_name: jupyterhub-hub
    environment:
      DOCKER_NETWORK_NAME: jupyterhub-network
      HUB_IP: jupyterhub-hub
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${JUPYTERHUB_HOSTNAME}"
    restart: on-failure
    networks:
      - jupyterhub-network

  reverse-proxy:
    image: traefik
    container_name: jupyterhub-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./reverse-proxy/certs:/etc/certs
      - proxy-tmp:/tmp
    restart: on-failure
    networks:
      - jupyterhub-network

networks:
  jupyterhub-network:
    name: jupyterhub-network

volumes:
  proxy-tmp:
    name: jupyterhub-proxy-tmp